[programs.localnet]
contract_sol_tweet = "3gkLpMFoLq2LqtbLFzZQMzNUc8bapigveCp7HiftvDXD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/krg/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
