[programs.devnet]
contract_sol_tweet = "FfpFvZt8RBg57TTMSe36saHKLTngeJzKLcc9dMDrgR8t"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/krg/.config/solana/wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
